# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springtestdb?createDatabaseIfNotExist=true
    username: springtest
    password: 12345
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
